# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/user/application_security/secret_detection/pipeline/configure
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence

stages:
  - test
  - secret-detection
  - build
  - scan
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"
  SECRET_DETECTION_ENABLED: 'true'
  DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE
  DOCKER_HUB_IMAGE: $DOCKER_HUB_USERNAME/blendscan

# Security scanning
sast:
  stage: test

secret_detection:
  stage: secret-detection

include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
  - template: Security/Container-Scanning.gitlab-ci.yml

# Docker build stage
build:
  stage: build
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  variables:
    DOCKER_BUILDKIT: 1
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - |
      if [ -n "$DOCKER_HUB_USERNAME" ] && [ -n "$DOCKER_HUB_PASSWORD" ]; then
        echo "Docker Hub credentials found, logging in..."
        echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
        export DOCKER_HUB_ENABLED=true
      else
        echo "Docker Hub credentials not found, skipping Docker Hub operations"
        export DOCKER_HUB_ENABLED=false
      fi
  script:
    # Build for GitLab Container Registry
    - docker build --tag $DOCKER_IMAGE_NAME:$CI_COMMIT_SHA .
    - docker build --tag $DOCKER_IMAGE_NAME:latest .

    # Build for Docker Hub (conditional)
    - |
      if [ "$DOCKER_HUB_ENABLED" = "true" ]; then
        echo "Building images for Docker Hub..."
        docker build --tag $DOCKER_HUB_IMAGE:$CI_COMMIT_SHA .
        docker build --tag $DOCKER_HUB_IMAGE:latest .
      fi

    # Tag version if on main branch
    - |
      if [ "$CI_COMMIT_BRANCH" = "main" ]; then
        VERSION=$(grep -o '"version": ([0-9, ]*' __init__.py | grep -o '[0-9, ]*' | tr -d ' ' | tr ',' '.')
        docker tag $DOCKER_IMAGE_NAME:latest $DOCKER_IMAGE_NAME:v$VERSION
        if [ "$DOCKER_HUB_ENABLED" = "true" ]; then
          docker tag $DOCKER_HUB_IMAGE:latest $DOCKER_HUB_IMAGE:v$VERSION
        fi
      fi

    # Push to registries
    - docker push $DOCKER_IMAGE_NAME:$CI_COMMIT_SHA
    - docker push $DOCKER_IMAGE_NAME:latest
    - |
      if [ "$DOCKER_HUB_ENABLED" = "true" ]; then
        echo "Pushing to Docker Hub..."
        docker push $DOCKER_HUB_IMAGE:$CI_COMMIT_SHA
        docker push $DOCKER_HUB_IMAGE:latest
      fi

    # Push version tag if on main branch
    - |
      if [ "$CI_COMMIT_BRANCH" = "main" ]; then
        VERSION=$(grep -o '"version": ([0-9, ]*' __init__.py | grep -o '[0-9, ]*' | tr -d ' ' | tr ',' '.')
        docker push $DOCKER_IMAGE_NAME:v$VERSION
        if [ "$DOCKER_HUB_ENABLED" = "true" ]; then
          docker push $DOCKER_HUB_IMAGE:v$VERSION
        fi
      fi
  rules:
    - if: $CI_COMMIT_BRANCH
    - if: $CI_COMMIT_TAG

# Container scanning
container_scanning:
  stage: scan
  variables:
    CI_APPLICATION_REPOSITORY: $DOCKER_IMAGE_NAME
    CI_APPLICATION_TAG: $CI_COMMIT_SHA
  dependencies:
    - build

# Deploy to Docker Hub (for releases)
deploy:docker-hub:
  stage: deploy
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  before_script:
    - |
      if [ -z "$DOCKER_HUB_USERNAME" ] || [ -z "$DOCKER_HUB_PASSWORD" ]; then
        echo "ERROR: Docker Hub credentials not configured"
        exit 1
      fi
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
  script:
    - echo "Deploying BlendScan v$CI_COMMIT_TAG to Docker Hub"
    - docker pull $DOCKER_HUB_IMAGE:latest
    - docker tag $DOCKER_HUB_IMAGE:latest $DOCKER_HUB_IMAGE:$CI_COMMIT_TAG
    - docker push $DOCKER_HUB_IMAGE:$CI_COMMIT_TAG
    - docker push $DOCKER_HUB_IMAGE:latest
  rules:
    - if: $CI_COMMIT_TAG
      when: manual
  environment:
    name: docker-hub
    url: https://hub.docker.com/r/$DOCKER_HUB_USERNAME/blendscan