# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/user/application_security/secret_detection/pipeline/configure
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence

stages:
  - test
  - secret-detection
  - build
  - scan
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"
  SECRET_DETECTION_ENABLED: 'true'
  DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE
  DOCKER_HUB_IMAGE: $DOCKER_HUB_USERNAME/blendscan

# Security scanning
sast:
  stage: test

secret_detection:
  stage: secret-detection

include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
  - template: Security/Container-Scanning.gitlab-ci.yml

# Docker build stage
build:
  stage: build
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  variables:
    DOCKER_BUILDKIT: 1
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - |
      if [ -n "$DOCKER_HUB_USERNAME" ] && [ -n "$DOCKER_HUB_PASSWORD" ]; then
        echo "Docker Hub credentials found, logging in..."
        echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
        export DOCKER_HUB_ENABLED=true
      else
        echo "Docker Hub credentials not found, skipping Docker Hub operations"
        export DOCKER_HUB_ENABLED=false
      fi
  script:
    # Build once and tag multiple times to save time
    - echo "Building Docker image..."
    - docker build --tag blendscan-temp .

    # Tag for GitLab Container Registry
    - docker tag blendscan-temp $DOCKER_IMAGE_NAME:$CI_COMMIT_SHA
    - docker tag blendscan-temp $DOCKER_IMAGE_NAME:latest

    # Tag for Docker Hub (conditional)
    - |
      if [ "$DOCKER_HUB_ENABLED" = "true" ]; then
        echo "Tagging images for Docker Hub..."
        docker tag blendscan-temp $DOCKER_HUB_IMAGE:$CI_COMMIT_SHA
        docker tag blendscan-temp $DOCKER_HUB_IMAGE:latest
      fi

    # Extract and tag version if on main branch
    - |
      if [ "$CI_COMMIT_BRANCH" = "main" ]; then
        echo "Extracting version from project files..."
        # Try multiple patterns to find version
        if [ -f "__init__.py" ]; then
          VERSION=$(grep -E '(version|__version__)' __init__.py | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -1)
        elif [ -f "setup.py" ]; then
          VERSION=$(grep -E 'version=' setup.py | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -1)
        elif [ -f "pyproject.toml" ]; then
          VERSION=$(grep -E 'version =' pyproject.toml | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -1)
        fi

        if [ -n "$VERSION" ]; then
          echo "Found version: $VERSION"
          docker tag blendscan-temp $DOCKER_IMAGE_NAME:v$VERSION
          if [ "$DOCKER_HUB_ENABLED" = "true" ]; then
            docker tag blendscan-temp $DOCKER_HUB_IMAGE:v$VERSION
          fi
        else
          echo "No version found in project files, skipping version tagging"
        fi
      fi

    # Push to registries
    - docker push $DOCKER_IMAGE_NAME:$CI_COMMIT_SHA
    - docker push $DOCKER_IMAGE_NAME:latest
    - |
      if [ "$DOCKER_HUB_ENABLED" = "true" ]; then
        echo "Pushing to Docker Hub..."
        docker push $DOCKER_HUB_IMAGE:$CI_COMMIT_SHA
        docker push $DOCKER_HUB_IMAGE:latest
      fi

    # Push version tag if it exists
    - |
      if [ "$CI_COMMIT_BRANCH" = "main" ] && [ -n "$VERSION" ]; then
        echo "Pushing version tag: v$VERSION"
        docker push $DOCKER_IMAGE_NAME:v$VERSION
        if [ "$DOCKER_HUB_ENABLED" = "true" ]; then
          docker push $DOCKER_HUB_IMAGE:v$VERSION
        fi
      fi

    # Clean up temporary image
    - docker rmi blendscan-temp || true
  rules:
    - if: $CI_COMMIT_BRANCH
    - if: $CI_COMMIT_TAG

# Container scanning
container_scanning:
  stage: scan
  variables:
    CI_APPLICATION_REPOSITORY: $DOCKER_IMAGE_NAME
    CI_APPLICATION_TAG: $CI_COMMIT_SHA
  dependencies:
    - build

# Deploy to Docker Hub (for releases)
deploy:docker-hub:
  stage: deploy
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  before_script:
    - |
      if [ -z "$DOCKER_HUB_USERNAME" ] || [ -z "$DOCKER_HUB_PASSWORD" ]; then
        echo "ERROR: Docker Hub credentials not configured"
        exit 1
      fi
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
  script:
    - echo "Deploying BlendScan v$CI_COMMIT_TAG to Docker Hub"
    - docker pull $DOCKER_HUB_IMAGE:latest
    - docker tag $DOCKER_HUB_IMAGE:latest $DOCKER_HUB_IMAGE:$CI_COMMIT_TAG
    - docker push $DOCKER_HUB_IMAGE:$CI_COMMIT_TAG
    - docker push $DOCKER_HUB_IMAGE:latest
  rules:
    - if: $CI_COMMIT_TAG
      when: manual
  environment:
    name: docker-hub
    url: https://hub.docker.com/r/$DOCKER_HUB_USERNAME/blendscan